apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: aspnet
  name: aspnet
  namespace: sv-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnet
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aspnet
    spec:
      containers:
      - image: 839791487044.dkr.ecr.eu-west-1.amazonaws.com/aspnet:IMG
        name: aspnet
        resources:
          requests:
            memory: "150M"
            cpu: "20m"
          limits:
            memory: "3G"
            cpu: "850m"
        ports:
        - containerPort: 80
status: {}
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: aspnet
  name: aspnet
  namespace: sv-apps
spec:
  selector:
    app: aspnet
  ports:
  - port: 80
    name: aspnet
    targetPort: 80
  type: ClusterIP
